# CLIENT - OTEL COLLECTOR - BACKEND
  # RECEIVERS VE EXPORTERS "CLIENT VE OTEL COLLECTOR" ARASINDA VEYA "OTEL COLLECTOR VE BACKEND" ARASINDA VARDIR.
  # BUNLAR BİRBİRLERİYLE KARIŞTIRILMAMALIDIR.

  # RECEIVERS KISMINDA BELİRTİLENLERN CLIENT İLE OTEL COLLECTOR ARASINDAKİ KONFİGÜRASYONU BELİRTİR.
    # PUSH BASED RECEIVERS VEYAHUT PULL BASED RECEIVERS OLABİLİR.
      # PUSH BASED RECEIVERS --> CLIENT VERİYİ OTEL COLLECTOR'A PUSH EDER. BURADA EXPORTER İSE CLIENT TARAFINDA BELİRTİLİR.
        # BURADA EXPORTER CLIENT TARAFIDIR ÖRNEĞİN "import { OTLPTraceExporter } from '@opentelemetry/exporter-trace-otlp-grpc'"
      # PULL BASED RECEIVERS --> OTEL COLLECTOR VERİYİ CLIENT'DAN PULL EDER.
        # BURADA EXPORTER KAVRAMI YOKTUR.

  # EXPORTERS KISMINDA BELİRTİLENLER OTEL COLLECTOR İLE BACKEND ARASINDAKİ KONFİGÜRASYONU BELİRTİR.
    # PUSH BASED EXPORTERS VEYAHUT PULL BASED EXPORTERS OLABİLİR.
      # PUSH BASED EXPORTERS --> OTEL COLLECTOR VERİYİ BACKEND'E PUSH EDER.
        # BURADA RECEIVER BACKEND TARAFIDIR ÖRNEĞİN JAEGER İÇİN "jaeger-all-in-one" CONTAINER'I.
      # PULL BASED EXPORTERS --> BACKEND VERİYİ OTEL COLLECTOR'DAN PULL EDER.İ
        # BURADA RECEIVER KAVRAMI YOKTUR.

receivers:
  otlp: # --> PUSH BASED RECEIVER
    protocols:
      grpc: # DEFAULT --> 4317
        endpoint: "0.0.0.0:4317" # "ANLAMI --> COLLECTOR 4317 PORTUNU AÇ VE BURADA VERİ BEKLE. VERİ BEKLEYECEĞİN ADRESLER ŞUAN İÇİN TÜM IP ADRESLERİ."
      http: # DEFAULT --> 4318
        endpoint: "0.0.0.0:4318" # "ANLAMI --> COLLECTOR 4318 PORTUNU AÇ VE BURADA VERİ BEKLE. VERİ BEKLEYECEĞİN ADRESLER ŞUAN İÇİN TÜM IP ADRESLERİ."

# PUSH BASED BACKENDS **> VERİLER COLLECTOR'DAN BACKEND'E PUSH EDİLİR. YANİ COLLECTOR BELİRTİLEN ENDPONIT'E (HEDEF BACKEND) VERİYİ PUSH EDER.
# PULL BASED BACKENDS --> BACKEND VERİLERİ COLLECTOR'DAN PULL EDER. YANİ COLLECTOR'UN KENDİ AÇTIĞI ADRESTİR. HEDEF BACKEND BU ENDPOINT'I SCRAPE EDER. PULL BASED EXPORTER'LAR COLLECTOR İÇİNDE ÇALIŞIRLAR.
# BU YÜZDEN OTLE-COLLECTOR'U SCRAPE EDERLER.
exporters:
  otlp:
    endpoint: "http://otel-collector:4317"
    tls:
      insecure: true

  # Data sources: traces
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

  # Data sources: metrics
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: default

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [otlp/jaeger]
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [prometheus]